version: "2"
services:
  client:
    build: ./webapp
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/webapp
      - /webapp/node_modules
    links:
      - api
    networks: 
      - webappnetwork
  api:
    build: ./server
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongodb
    networks: 
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - webappnetwork
networks:
    webappnetwork:
        driver: bridge